services:
  duckdns:
    image: linuxserver/duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Chisinau
      - SUBDOMAINS=temptake-mqtt.duckdns.org,temptake-server.duckdns.org
      - TOKEN=${DUCKDNS_TOKEN}
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "$MQTT_BROKER_PORT:$MQTT_BROKER_PORT"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  db:
    image: postgres:17
    user: ${DB_USER}
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mqtt-handler:
    build: ./TempTake-MQTT
    deploy:
      replicas: 1
    depends_on:
      db:
        condition: service_healthy
      mosquitto:
        condition: service_started
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MQTT_BROKER_PORT=$MQTT_BROKER_PORT
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  server:
    build: ./TempTake-Server
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - INTERNAL_SECRET=${INTERNAL_SECRET}

  telegram:
    build: ./TempTake-Telegram
    depends_on:
      server:
        condition: service_started
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=${SERVER_PORT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - INTERNAL_SECRET=${INTERNAL_SECRET}

volumes:
  db-data:
